version: '3.4'

services:
  vizualizer:
    image: dockersamples/visualizer
    volumes:
      - src=/var/run/docker.sock
      - dst=/var/run/docker.sock
    ports:
      - "8080:8080/tcp"
    deploy:
      replicas: 1      
      placement:
        constraints:
          - node.role == manager
          